feat: created unit tests for ayudantía
IIC2513-2021-2/soundify pull request #20
Opened 2021-11-03 14:33 UTC by dasolari

## Description
- Added tests and modified project to display in testing assistantship.
- Many comments where added in order to explain the code during the assistantship. They will be deleted later 🙈 

## Requirements
- A small change was made to the data base, so a __migration__ is required.

## Additional
The tests do not pass on purpose. This is to show that the snapshot test caught a change in the name of an attribute and therefore, could cause an error in the frontend.

Code written by @FranciscaOtero and @dasolari using VSCode live share.

2021-11-03 15:01 UTC, sivicencio requested changes
En general súper bien. Dejé algunas sugerencias y cambios menores solamente.

2021-11-03 16:37 UTC, dasolari commented on yarn.lock
> -
Ok 👍

2021-11-03 16:38 UTC, dasolari commented on src/views/artists/show.html.ejs
> +<h3>Formed at: <%= artist.foundedIn %></h3>
Ups jeje, lo corrijo ahora.

2021-11-03 16:40 UTC, dasolari commented on src/routes/api/__tests__/auth.test.js
> +    describe('When user data is valid', () => {
Para los describe lo deje con mayúscula y para los test con minúscula. Lo dejo todo igual?

2021-11-03 16:42 UTC, dasolari commented on src/routes/api/__tests__/auth.test.js
> +      test('when email is not registered in the data base, responds with 404 status code', async () => {
Se me pasó. Ahora lo arreglo

2021-11-03 16:53 UTC, dasolari commented on yarn.lock
> -
Corrí yarn install pero no pasó nada. Revisé y están bien las versiones.

2021-11-03 17:03 UTC, FranciscaOtero commented on src/routes/api/auth.js
> +  delete userData.password;
Oka! Me parece cambiarlo, lo voy a arreglar.

2021-11-03 18:04 UTC, FranciscaOtero commented on src/routes/api/__tests__/auth.test.js
> +      test('when email is registered and password is correct, responds with 200 status code', () => {
Sii toda la razón, es redundante.

2021-11-03 18:24 UTC, sivicencio commented on src/routes/api/__tests__/auth.test.js
> +    describe('When user data is valid', () => {
Está bien si sigues esa convención no más.

2021-11-03 20:31 UTC, sivicencio commented on yarn.lock
> -
Sí, creo que no me expresé bien. Me refería a que este cambio (líneas eliminadas) está súper bien aquí.

2021-11-03 21:15 UTC, dasolari commented on src/routes/api/__tests__/auth.test.js
> +      test('when email exists and password is incorrect, responds with 401 status code', async () => {
Al final @FranciscaOtero mantuvo el test pero le acortó el nombre.

2021-11-05 09:32 UTC, sivicencio approved these changes

2021-11-08 13:32 UTC, merged