feat/uploadFiles
IIC2513-2021-2/soundify pull request #25
Opened 2021-11-24 23:58 UTC by pedroherreraj

## Description

En esta PR se incluye el upload files a la página. Para esto le agregue un default value al atributo *cover* de **Albúm**. La forma de manejo de archivos es mediante cloudinary, por eso se importa esa librería. Agregue un nuevo endpoint, el cual corresponde al *patch* de **Albúm**, en el cual se puede cambiar el cover del Albúm. 

## Requirements

Agregar al .env CLOUDINARY_URL, con el valor de la cuenta de uno.

2021-11-25 02:45 UTC, valeeeriquelme requested changes

2021-11-25 02:45 UTC, valeeeriquelme commented on src/routes/api/albums.js
> +  const { cloudinary } = ctx.state;
Falta revisar si existe el album. Esto puede ser reemplazado por un router.params, pero faltaría implementar eso en ese caso.

2021-11-26 22:19 UTC, sivicencio requested changes
Una pequeña sugerencia para evitar código duplicado, y un comentario para el video de la cápsula.

2021-11-26 22:19 UTC, sivicencio commented on src/routes/api/albums.js
> +    const album = await ctx.orm.album.findByPk(ctx.params.id);
Ya deberías tener disponible `ctx.state.album` en este punto, por lo que esto sólo podría ser:
```suggestion
    const { album } = ctx.state;
```

2021-11-26 22:19 UTC, sivicencio commented on src/app.js
> +  if (process.env.CLOUDINARY_URL) {
Sería bueno mencionar en el video de la cápsula que sólo es necesario tener esta variable de ambiente seteada para que cualquier llamada a `cloudinary` "funcione" con la cuenta que uno crea.

2021-11-28 12:40 UTC, sivicencio approved these changes

2021-11-28 21:32 UTC, valeeeriquelme approved these changes

2021-11-28 21:32 UTC, merged